# Game setup
WIDTH = 1280
HEIGHT = 720
FPS = 60

# Player settings
PLAYER_START_X = WIDTH // 2
PLAYER_START_Y = HEIGHT // 2
PLAYER_SIZE = 0.5
PLAYER_SPEED = 8
GUN_OFFSET_X = 0
GUN_OFFSET_Y = 0
PLAYER_HEALTH = 100
DAMAGE_COOLDOWN = 3

# Bullet settings
SHOOT_COOLDOWN = 10
BULLET_SCALE = 1
BULLET_SPEED = 50
BULLET_LIFETIME = 850

# Enemy settings
ENEMY_SPEED = 7
ENEMY_HEALTH = 100


